django_blog_projesi/article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard, name = "dashboard"),
    path('addarticle/',views.addarticle, name = "addarticle"),
    path('article/<int:id>',views.detail, name = "detail"),
    path('update/<int:id>',views.updateArticle, name = "update"),
    path('delete/<int:id>',views.deleteArticle, name = "delete"),
    path('',views.articles, name = "articles"),
    path('comment/<int:id>',views.addComment, name = "comment"),
]

django_blog_projesi/django_blog_projesi/urls.py
from django.contrib import admin
from django.urls import path, include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('about/', views.about, name = "about"),
    path('articles/',include("article.urls")),
    path('user/',include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_blog_projesi/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/',views.register, name = "register"),
    path('login/',views.loginUser, name = "login"),
    path('logout/',views.logoutUser, name = "logout"),
]

django_blog_projesi/article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete= models.CASCADE,verbose_name="Yazar")
    title = models.CharField(max_length=50,verbose_name="Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank=True, null= True,verbose_name="Makaleye fotoğraf ekleyin")
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name="Makale",related_name="comments")
    comment_author = models.CharField(max_length=50,verbose_name="İsim")
    comment_content = models.CharField(max_length=200,verbose_name="Yorum")
    comment_date = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        return self.comment_author
    class Meta:
        ordering = ['-comment_date']

    



    

django_blog_projesi/article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

django_blog_projesi/article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from .forms import ArticleForm
from .models import Article, Comment
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, "index.html")

def about(request):
    return render(request, "about.html")

def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles": articles})

    articles = Article.objects.all()
    return render(request, "articles.html",{"articles":articles})

@login_required(login_url= "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles":articles
    }
    return render(request,"dashboard.html",context)

@login_required(login_url= "user:login")
def addarticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False) # Objeyi oluştur fakat şu an kaydetme diyoruz. (commit=False)
        article.author = request.user
        article.save()

        messages.success(request,"Makale başarıyla oluşturuldu.")
        return redirect("index")
    return render(request, "addarticle.html",{"form":form})

def detail(request,id):
    # article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article,id = id)
    comments = article.comments.all()
    return render(request,"detail.html",{"article":article,"comments":comments})

@login_required(login_url= "user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article, id = id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance=article)
    if form.is_valid():
        article = form.save(commit=False) # Objeyi oluştur fakat şu an kaydetme diyoruz. (commit=False)
        article.author = request.user
        article.save()

        messages.success(request,"Makale başarıyla güncellendi.")
        return redirect("article:dashboard")
    return render(request,"update.html",{"form":form})

@login_required(login_url= "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)
    article.delete()
    messages.success(request,"Makale başarıyla silindi.")
    return redirect("article:dashboard")

def addComment(request,id):
    article = get_object_or_404(Article,id = id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")

        newComment = Comment(comment_author = comment_author, comment_content = comment_content)
        newComment.article = article
        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))

django_blog_projesi/templates/about.html
{% extends 'layout.html' %}

{% block body %}

<h3>Hakkımda</h3>
<hr>

<p>Merhaba ben Battal Uçar. Uluslararası İlişkiler 4. sınıf öğrencisiyim. Şu an yazılım konusunda kendimi geliştirmeye uğraşıyorum ve bu benim ilk bağımsız olarak geliştirdiğim DJANGO web sayfası projesi.</p>
{% endblock body %}

django_blog_projesi/templates/addarticle.html
{% extends 'layout.html' %}

{% block body %}

    {% load crispy_forms_tags %}

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Makale Oluştur</h3>
            <hr>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.media}}

                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-primary">Makale Oluştur</button>
            </form>
        </div>
    </div>
{% endblock body %}

django_blog_projesi/templates/articles.html
{% extends 'layout.html' %}

{% block body %}

    <!-- Sidebar Widgets Column -->
            <div class="col-md-8">

                <!-- Search Widget -->
                <div class="card my-4">
                    <h5 class="card-header">Ara</h5>
                        <form>
                        {% csrf_token %}
                            <div class="input-group mb-0">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="inputGroup-sizing-default"></span>
                                </div>
                                <input type="search" class="form-control" aria-label="Default" aria-describedby="inputGroup-sizing-default" name="keyword" placeholder="Aramak istediğiniz kelimeyi giriniz...">
                                <button style="color:black"class="btn btn-outline-secondary" type="submit">Ara</button>
                        </form>
                    </div>
                </div>

    {% if articles %}
        {% for article in articles %}
        
            <div class="container">
                <div class="row">
                    
                    <!-- <div class="col-md-6 offset-md-3"> Ortalama-->

                    <!-- Post Content Column -->
                    <div class="col-lg-8">

                        <h2>Makaleler</h2><hr>
                        
                        <!-- Title -->
                        <a href="{% url 'article:detail' article.id %}"><h5 class="mt-4">{{article.title}}</h5></a>   

                        <!-- Author -->
                        <p class="lead">
                        <b>by</b> {{article.author}}
                        </p>
                        <hr>

                        <!-- Date/Time -->
                        <p>{{article.created_date}} tarihinde oluşturuldu.</p>
                        <hr>

                        <!-- Preview Image -->
                        {% if article.article_image %}
                            
                            <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="image">
                            
                        {% endif %}  

                        <!-- Post Content -->
                        <p class="lead">{{article.content|safe|truncatewords:10}}</p> 
                        <a href="{% url 'article:detail' article.id %}" class="btn btn-danger">Devamını oku...</a>
                        <hr>

                    </div>

        {% endfor %}
                </div>
            </div>
            
    {% else %}

        <div class="alert alert-danger">Makale Bulunamadı!</div>

    {% endif %}

{% endblock body %}

django_blog_projesi/templates/dashboard.html
{% extends 'layout.html' %}

{% block body %}

    <h3>Kontrol Paneli</h3>
    <hr>
    <p>Hoşgeldiniz, <strong>{{request.user.username}}</strong>!</p><br>

    {% if articles %}

        <table class="table">
            <thead>
                <tr>
                <th scope="col">ID</th>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">Created Time</th>
                <th scope="col">Güncelle</th>
                <th scope="col">Sil</th>
                </tr>
            </thead>
            <tbody>
                {% for article in articles  %}
                
                    <tr>
                        <th scope="row">{{article.id}}</th>
                        <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
                        <td>{{article.author.username}}</td>
                        <td>{{article.created_date}}</td>
                        <td><a class="btn btn-warning" href="{% url 'article:update' article.id %}">Güncelle</a></td>
                        <td><a class="btn btn-danger" href="{% url 'article:delete' article.id %}">Sil</a></td>
                    </tr>
                
                {% endfor %}
                
            </tbody>
        </table>
    
    {% else %}
        <div class="alert alert-danger">Henüz bir Makaleniz Bulunmuyor!</div>
    
    {% endif %}

    <a class= "btn btn-danger" href="{% url 'article:addarticle' %}">Makale Ekle</a>
{% endblock body %}

django_blog_projesi/templates/detail.html
{% extends 'layout.html' %}

{% block body %}
<div class="container">

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h2 class="mt-4">{{article.title}}</h2>

        <!-- Author -->
        <p class="lead">
          by {{article.author}}
        </p>

        <hr>

        <!-- Date/Time -->
        <p>{{article.created_date}} tarihinde oluşturuldu.</p>

        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}
        
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
        
        {% endif %}

        <!-- Post Content -->
        <p class="lead">{{article.content|safe}}</p>

        <hr>

        <h4>Yorumlar</h4>
        <hr>
        {% if comments %}
          {% for comment in comments  %}
            <div class="media mb-4">
              <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">{{comment.comment_author}}</h5>
                {{comment.comment_date}}<br>
                {{comment.comment_content}}
              </div>
            </div>
          {% endfor %}

        {% else %}
        
          <div class="alert alert-warning">Bu makaleye henüz herhangi bir yorum yapılmamış. Siz yapın!</div>
        
        {% endif %}

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Yorum ekle:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'article:comment' article.id %}">
              {% csrf_token %}
              <div class="form-group">
                <label for="formGroupExampleInput">İsim:</label>
                <input name="comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi giriniz...">
              </div>
              <div class="form-group">
                <label for="Yorum">Yorum:</label>
                <textarea placeholder="Yorumunuzu buraya girebilirsiniz..."name="comment_content" class="form-control" id="Yorum"rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Ekle</button>
            </form>
          </div>
        </div>

      </div>

    </div>

</div>
{% endblock body %}

django_blog_projesi/templates/index.html
{% extends 'layout.html' %}

{% block body %}
    <div class= "jumbotron text-center">
        <h3>Battal Uçar'ın bloguna hoşgeldiniz!</h3>
        <p>Bu blogda yazılım hakkında çeşitli bilgileri bulabilirsiniz.</p>
    </div>
{% endblock body %}

django_blog_projesi/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Battal Blog</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>
<body>
    {% include "includes/navbar.html" %}
    <div class="container" style="margin-top:100px; margin-bottom:100px;">
    {% if messages %}
    
        {% for message in messages %}
            {% if message.tags == "info" %} <!-- DANGER gösterimi için 'INFO' çağrıldığında danger ayarı yapalım-->
                <div class="alert alert-danger">{{ message }}</div>
            {% else %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endif %}
        
        {% endfor %}
    
    {% endif %}
    

    {% block body %}


    {% endblock body %}
    
    
    </div>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/run_prettify.js'%}}"></script>

</html>

django_blog_projesi/templates/login.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Giriş Yap</h3>
            <hr>

            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-primary">Giriş Yap</button>
            </form>
        </div>
    </div>


{% endblock body %}

django_blog_projesi/templates/register.html
{% extends 'layout.html' %}

{% block body %}
{% load crispy_forms_tags %}

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Kayıt Ol</h3>
            <hr>

            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-primary">Kayıt Ol</button>
            </form>
        </div>
    </div>

{% endblock body %}

django_blog_projesi/templates/update.html
{% extends 'layout.html' %}

{% block body %}

    {% load crispy_forms_tags %}

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Makale Güncelle</h3>
            <hr>

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.media}}

                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-primary">Güncelle</button>
            </form>
        </div>
    </div>
{% endblock body %}